name: Jamison Jones
favicon: null
layout_spectrum: 0.25795
typography_spectrum: 0.64822
title: Jamison Jones
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73012941-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cddae7'
    - '#202020'
    - '#403e3f'
    - '#9aa7b4'
    - '#848580'
  brandStrength: 0.625
  lightness: 0.1875
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
