typography_spectrum: 0.48934
color:
  brandColors:
    - '#cddae7'
    - '#202020'
    - '#403e3f'
    - '#9aa7b4'
    - '#848580'
  brandStrength: 0.625
  lightness: 0.1875
  saturation: 0.625
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25795
analytics:
  google: UA-73012941-1
  facebook: null
  twitter: null
name: Jamison Jones
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Jamison Jones
description: Do Your Creative Best with What You Have.
purpose: []
