name: jamisonjones
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7126696100458503
title: Jamison Jones
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73012941-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffd'
    - '#4e658e'
    - '#d7d1b6'
    - '#010412'
    - '#722614'
  brandStrength: 0.625
  lightness: 0.1875
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
