name: Jamison Jones
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48934
navigation:
  - name: YouTube Channel
    url: 'http://youtube.com/jamisonjones'
    type: external
  - name: Clothing Brand
    url: 'http://generosityspeaks.com'
    type: external
  - name: Social Media
    id: e4547a0b-7d5e-4d3a-b396-c6ee6af1a5fa
    type: content
title: Jamison Jones
description: Do Your Creative Best with What You Have.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73012941-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cddae7'
    - '#202020'
    - '#403e3f'
    - '#9aa7b4'
    - '#848580'
  brandStrength: 0.625
  lightness: 0.1875
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
