name: jamisonjones
favicon: null
layout_spectrum: 0.2635412828531116
typography_spectrum: 0.7126696100458503
title: Jamison Jones
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5415059397928417
  lightness: 0.09958128677681088
  saturation: 0.7554613838437945
  rhythmicContrast: 0.3178857988677919
purpose: []
